### ISSUE TITLE
IntranetUserJS: Add links to record in Finna testaus

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-cart-link-to-record-in-finna#1]
IntranetUserJS: Add links to record in Finna

Testaus Nexteillä:

Poista intranetUserJS-asetuksesta rimpsut
/// Lisää tietueen perustiedot-näytölle valikkoriville loppuun Avaa Finnassa -nappula. ///
ja
// Finna-verkkokirjastolinkkien lisääminen ostoskoriin //

Konfiguroi pluginiin määrittelyssä oikea kimpan Finna-osoite.
Aktivoi plugin.

Testattava, että kori-toiminnossa näkyy ja toimii emo- ja osakohteille omat Finna-linkkinappinsa ja että tietueen perusnäytöllä toimii avaa Finnassa-nappi.

**Comment by AnneliO** [comment]
Seuranta kimpoista. Kommentoi, kun muutos tehty ja testattu omassa kimpassa.

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by pknuuti** [comment]
Nextilläkö tätä testataan?

**Comment by AnneliO** [comment]
> Nextilläkö tätä testataan?

Hmm.. joo, niin se muuten taitaa olla siellä.

**Comment by pknuuti** [comment]
Ei pysty testaamaan toimivuutta, kun tiedonhaku nextillä ei toimi.

**Comment by pknuuti** [comment]
Tiedonhaku toimii nyt, mutta kori-toiminnossa on jotain outoa. Vaikka valitsen useamman nimekkeen koriin, siellä näkyy vain yksi. Kori-toiminnon kuvakkeessa näkyy useampi nimeke, joille ei tapahdu mitään, kun yritän tyhjentää korin. Aina vain näien saman nimekkeen korissa.

![2023kuvat 494](https://github.com/user-attachments/assets/4c875cf0-1ed1-4449-9d5e-ba83f3f099ca)

**Comment by pknuuti** [comment]
Onko tarkoitus, että hakutulokseen tulee jokaisen nimekkeen kohdalle Avaa Finnassa-painike?

**Comment by AnneliO** [comment]
> Onko tarkoitus, että hakutulokseen tulee jokaisen nimekkeen kohdalle Avaa Finnassa-painike?

Ainakaan aiemmin näin ei ollut.

**Comment by AnneliO** [comment]
Siili-nextillä tuntuisi toimivan oikein (myös korissa). Ainoastaan tosiaan muutoksena entiseen, Avaa Finnassa -nappula näkyy nyt myös hakutuloslistalla:

![kuva](https://github.com/user-attachments/assets/ba80b221-c8c0-422c-b267-19603a33d2a7)

Mutta haittaako se, että se näkyy myös siinä?

**Comment by AnneliO** [comment]
> Tiedonhaku toimii nyt, mutta kori-toiminnossa on jotain outoa. Vaikka valitsen useamman nimekkeen koriin, siellä näkyy vain yksi. Kori-toiminnon kuvakkeessa näkyy useampi nimeke, joille ei tapahdu mitään, kun yritän tyhjentää korin. Aina vain näien saman nimekkeen korissa.
> 
> ![2023kuvat 494](https://private-user-images.githubusercontent.com/73887264/360358665-4c875cf0-1ed1-4449-9d5e-ba83f3f099ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTcxNTUsIm5iZiI6MTcyNDMxNjg1NSwicGF0aCI6Ii83Mzg4NzI2NC8zNjAzNTg2NjUtNGM4NzVjZjAtMWVkMS00NDQ5LTlkNWUtYmE4M2YzZjA5OWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNjEwODMwMmNkYjRlZWIxNjgxM2IyMTM2NWJhMjczMWY3ZDJhNWQ2MGExYjhhZjE1Y2M4NjZiYjdkOGFmYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J9gekzEcK7VdZzKi5pXPfHU_Mtk2orUWw42ieIt_oas)

Mulla vaara-nextillä Kori toimii oikein. Oletko Päivi tehdä päivityksen ctrl+F5:lla? Jos sinne on jäänyt välimuistiin jotain tauhkaa vaikka?

**Comment by pknuuti** [comment]
Joo, nyt näyttäis toimivan Vaaran nextillä kuten pitääkin. Avaa Finnassa-nappi toimii kaikissa niissä paikoissa missä sitä näin.

**Comment by ReettaSiili** [comment]
Anneli testasikin jo Siilin puolesta toimivaksi :)
Lisähuomiot: Finna-linkki myös hakutuloslistalla on ihan hyvä juttu, mutta loogisuuden vuoksi osakohteella voisi silloin näkyä siinä myös Avaa emokohde Finnassa -linkki, kuten korissa.
Miksiköhän next ei näytä yläpalkissa ostoskorin sisällön määrää numeroina, kuten tuotannossa?

**Comment by lmstrand** [comment]
Korilinkkien javascript tiketistä https://github.com/KohaSuomi/Koha/issues/1193. Tuo aiheuttaa linkkien näkymisen hakutuloksissakin ilmeisesti.

**Comment by lmstrand** [comment]
Pluginin rimpsua on muutettu pluginia varten, jonka takia linkkinapit päätyvät hakutuloksiinkin. Poistetaanko linkki hakutuloksista? Ainakin tiivistäisi hieman.

**Comment by lmstrand** [comment]
Lisäsin linkkien luontiin tarkistuksen, että ollaan kori-sivulla. Nyt napit eivät päädy hakutuloksiin ja on tiiviimpää. Tehdään tuosta hakutulosnäytöstä vaikka uusi tiketti, jos sitä jäädään kaipaamaan?

**Comment by lmstrand** [comment]
ps. mulla näkyy siili-nextillä numerona määrä ostoskorissa. Olisiko selainvälimuistijuttu.

**Comment by atarnus** [comment]
Outi-nextillä laitettu kuntoon ja toimii.

**Comment by LeenaKinnunen** [comment]
Lapin nextillä plugin käytössä ja toimii. Hakutulossivulla ei näy Siilin tapaista Avaa Finnassa-painiketta, mutta ei minusta ole tarpeenkaan.

**Comment by ElinaUotila** [comment]
Kirkesissä määritykset kunnossa ja toimii.

**Comment by LastuJanneS** [comment]
Lastussa käytössä ja toimii kuten pitää.

**Comment by AnneliO** [comment]
Tämä on nyt kunnossa kaikissa kimpoissa.
